name: manage-azure-policy-10c958c7
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_from_groupId(blob)_bcb9fc7d-cb1f-464b-a6ce-d671a6583290/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_record)_from_groupId(redisCache)_72ee238d-71c9-449b-b299-3680e9ffabd2/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_from_groupId(redisEnterprise)_16e25b0c-4d35-490b-81f9-8f980543a85b/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_from_groupId(registry)_1847ac82-fc0a-4745-b163-670bbe009a24/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_for_AKS_from_groupId(management)_1847ac82-fc0a-4745-b163-670bbe009a32/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_from_groupId(iotHub)_e36bea98-09cf-48c1-822a-958f756c4bf5/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_from_groupId(iotDps)_e36bea98-09cf-48c1-822a-958f756c4c00/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_for_IoT_Central_from_groupId(IoTApps)_e36bea98-09cf-48c1-822a-958f756c4c0b/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_for_ADX_from_groupId(cluster)_e36bea98-09cf-48c1-822a-958f756c4c16/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_for_ADT_from_groupId(API)_773f8c02-7b5e-4258-a556-6dfa6da56f9a/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_for_Event_Grid_from_groupId(domain)_773f8c02-7b5e-4258-a556-6dfa6da56fa5/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_for_Event_Grid_from_groupId(topic)_773f8c02-7b5e-4258-a556-6dfa6da56fb0/**'
#      - 'policies/DINE_create_private_endpoint_resource(A_records)_for_Event_Hubs_from_groupId(namespace)_773f8c02-7b5e-4258-a556-6dfa6da56fbb/**'
#      - .github/workflows/manage-azure-policy-10c958c7.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_10c958c7}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/DINE_create_private_endpoint_resource(A_records)_from_groupId(blob)_bcb9fc7d-cb1f-464b-a6ce-d671a6583290/**
          policies/DINE_create_private_endpoint_resource(A_record)_from_groupId(redisCache)_72ee238d-71c9-449b-b299-3680e9ffabd2/**
          policies/DINE_create_private_endpoint_resource(A_records)_from_groupId(redisEnterprise)_16e25b0c-4d35-490b-81f9-8f980543a85b/**
          policies/DINE_create_private_endpoint_resource(A_records)_from_groupId(registry)_1847ac82-fc0a-4745-b163-670bbe009a24/**
          policies/DINE_create_private_endpoint_resource(A_records)_for_AKS_from_groupId(management)_1847ac82-fc0a-4745-b163-670bbe009a32/**
          policies/DINE_create_private_endpoint_resource(A_records)_from_groupId(iotHub)_e36bea98-09cf-48c1-822a-958f756c4bf5/**
          policies/DINE_create_private_endpoint_resource(A_records)_from_groupId(iotDps)_e36bea98-09cf-48c1-822a-958f756c4c00/**
          policies/DINE_create_private_endpoint_resource(A_records)_for_IoT_Central_from_groupId(IoTApps)_e36bea98-09cf-48c1-822a-958f756c4c0b/**
          policies/DINE_create_private_endpoint_resource(A_records)_for_ADX_from_groupId(cluster)_e36bea98-09cf-48c1-822a-958f756c4c16/**
          policies/DINE_create_private_endpoint_resource(A_records)_for_ADT_from_groupId(API)_773f8c02-7b5e-4258-a556-6dfa6da56f9a/**
          policies/DINE_create_private_endpoint_resource(A_records)_for_Event_Grid_from_groupId(domain)_773f8c02-7b5e-4258-a556-6dfa6da56fa5/**
          policies/DINE_create_private_endpoint_resource(A_records)_for_Event_Grid_from_groupId(topic)_773f8c02-7b5e-4258-a556-6dfa6da56fb0/**
          policies/DINE_create_private_endpoint_resource(A_records)_for_Event_Hubs_from_groupId(namespace)_773f8c02-7b5e-4258-a556-6dfa6da56fbb/**
