name: manage-azure-policy-37091f28
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Initiative_Create_private_endpoint_resources_from_multiple_groupIds_0db71c3018ba433da6c2e14e/**'
#      - .github/workflows/manage-azure-policy-37091f28.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_37091f28}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/Initiative_Create_private_endpoint_resources_from_multiple_groupIds_0db71c3018ba433da6c2e14e/**
